[package]
name = "alcmy"
version = "0.2.0"
edition = "2021"
description = "Unofficial Rust client for the Alchemy API"
license = "MIT"
repository = "https://github.com/yldfi/yldfi-rs/tree/main/crates/alcmy"
keywords = ["alchemy", "ethereum", "web3", "nft", "api"]
categories = ["api-bindings", "web-programming"]
readme = "README.md"

[dependencies]
alloy-primitives = { workspace = true }
bigdecimal = { workspace = true }
derive_more = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
solana-address = { workspace = true }
solana-hash = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
secrecy = { workspace = true }
url = { workspace = true, features = ["serde"] }
yldfi-common = { version = "0.1", path = "../yldfi-common" }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
